db:
  user: "test_user" # db user
  name: "server_room" # db name
  host: "127.0.0.1" # db host
  port: 3306 # db port
  timeout: 5s # read/write timeout

ntfy:
  host: "127.0.0.1" # ntfy host
  port: 8888 # ntfy port
  theme: "server-room" # ntfy theme

app:
  locale: "UTC" # "Europe/Moscow" # local time zone name
  logging:
    log_level: 1 # 1 - debug, 2 - info (default), 3 - warn, 4 - error, 5 - silent
    json_format: true # use JSON format if true
  healthcheck:
    port: 5555 # port for healthcheck HTTP-lightserver
  climate:
    check_db_every: 1m # 5m # time between db data checks
    temp_threshold: # temperature thresholds in degrees Celsius
      standart: 35.0
      high: 40.0
      urgent: 45.0
